FROM node:16.18.1 as builder

WORKDIR /web

COPY ./manage-system /web

RUN npm config set registry http://10.10.17.39:4873/
RUN npm install
RUN npm run build

FROM nginx:latest-brotli

COPY --from=builder --chown=nginx:nginx /web/dist   /

WORKDIR /usr/share/nginx/html

COPY --chown=nginx:nginx docker/conf/nginx.conf /etc/nginx/conf.d/default.conf
